### ISSUE TITLE
考虑把飞连的配置文件直接移植过来用？

### ISSUE THREAD

**Issue by jiechen257** [PinkD/corplink-rs#11]
不清楚具体实现，但如果能直接使用已有飞连的配置文件，那使用心智会少很多，再或者出一个配置字段的对比图，也方便迁移配置数据

**Comment by PinkD** [comment]
飞连的配置文件是指？

**Comment by jixiuf** [comment]
或许是官方版的飞连？   前段时间发现了 https://aur.archlinux.org/packages/corplink-bin
里面的deb文件下载下来，似乎也能正常使用，不过好像没遇到过需要手动写配置文件的场景 

看了下 里面的文件， 需要用 netorkmanager 管理网络（iwd等不行），另外用到了dnsmasq 管理域名解析(systemd-resolved不行)
https://github.com/PinkD/corplink-rs/issues/2#issuecomment-1530659519 前阵子 使用 corplink-rs 后无法走梯子的 问题， 配置好 dnsmasq 后 就能工作了，
给其他人做下参考

**Comment by jiechen257** [comment]
> 飞连的配置文件是指？

楼下这位帮我说了 :)

**Comment by PinkD** [comment]
> 使用 corplink-rs 后无法走梯子的 问题， 配置好 dnsmasq 后 就能工作了， 给其他人做下参考

dnsmasq 做了什么操作呢？飞连只会下发路由，理论上和 dnsmasq 没有任何关系

**Comment by jixiuf** [comment]
> 

我也不理解，它的  corplink.service 有一行 `ExecStartPost=/opt/Corplink/dnsmasq.sh`

```
#!/bin/bash
active=$(busctl list | grep org.freedesktop.NetworkManager.dnsmasq)
if [ -z "$active" ]; then
  if [ ! -d "/opt/Corplink/logs" ];then
    mkdir -p /opt/Corplink/logs
  fi
  /usr/sbin/dnsmasq --no-resolv --no-hosts --bind-interfaces --pid-file=/var/run/NetworkManager/dnsmasq.pid --listen-address=127.0.1.1 --cache-size=400 --conf-file=/dev/null --proxy-dnssec --enable-dbus=org.freedesktop.NetworkManager.dnsmasq --conf-dir=/etc/NetworkManager/dnsmasq.d > /opt/Corplink/logs/dnsmasq.log 2>&1
fi
```
里面内容是这样的，

**Comment by PinkD** [comment]
从命令行参数看，就是起了一个监听在 localhost 的 dnsmasq 服务，可能飞连依赖了这个，但是并没有看到具体的配置文件，所以不太确定这个服务到底是用来干什么的。除非需要从飞连的服务器上解析 dns ，否则应该直接用电脑本身的默认 dns 就足够了
