### ISSUE TITLE
关于配置项platform的相关value

### ISSUE THREAD

**Issue by Misaka-Mikodo** [PinkD/corplink-rs#16]
飞连，代码运行报错: 
`thread 'main' panicked at 'unsupported platform, please contact the developer', src/client.rs:287:17`
这个platform有什么可选项吗？

**Comment by PinkD** [comment]
https://github.com/PinkD/corplink-rs/blob/0463955d8b3c8e9e4694bf1e2b920a516a9b3acc/src/client.rs#L278-L289

这里只支持了飞书，因为我司只开了飞书。如果要支持其他的，需要抓包然后看下是怎么处理的，然后再实现一遍

**Comment by Misaka-Mikodo** [comment]
嗯……就是飞书，手机飞书扫描二维码到第三方登录后跳转到了SealSuite, 就没有进一步操作的指示了，terminal按下enter显示failed to login with method lark: 用户未登录.  

> https://github.com/PinkD/corplink-rs/blob/0463955d8b3c8e9e4694bf1e2b920a516a9b3acc/src/client.rs#L278-L289
> 
> 这里只支持了飞书，因为我司只开了飞书。如果要支持其他的，需要抓包然后看下是怎么处理的，然后再实现一遍

**Comment by PinkD** [comment]
这里的逻辑其实是这样的：飞连生成一个飞书的授权链接，然后用户用飞书登录，登录成功过后会记录下 token ，然后飞连就检查这次登录是否成功了。可能是登录完成过后跳到的新网站消耗了这次 token

**Comment by PinkD** [comment]
登录成功过后会弹出来一个 `corplink://base64_encoded_token` 的链接，应该是你的系统绑定了用某个程序打开这个链接，然后这次登录就被消耗掉了

**Comment by Misaka-Mikodo** [comment]
> 登录成功过后会弹出来一个 `corplink://base64_encoded_token` 的链接，应该是你的系统绑定了用某个程序打开这个链接，然后这次登录就被消耗掉了

了解了，我换个PC试试，

**Comment by Misaka-Mikodo** [comment]
> > 登录成功过后会弹出来一个 `corplink://base64_encoded_token` 的链接，应该是你的系统绑定了用某个程序打开这个链接，然后这次登录就被消耗掉了
> 
> 了解了，我换个PC试试，

看上去是的，我把验证链接发到移动端设备再验证就成功了！ 🎉 @PinkD
