### ISSUE TITLE
改为纯 Rust 实现

### ISSUE THREAD

**Issue by lz1998** [PinkD/corplink-rs#17]
可以考虑删除 uapi，直接用 Rust 实现的 wireguard
https://github.com/lz1998/wg-rs

**Comment by PinkD** [comment]
看了下这个库封装有点奇怪，不太方便使用。而且测速用的 scp ，没有参考价值，我可能会优先考虑 [cloudflare/boringtun](https://github.com/cloudflare/boringtun)

**Comment by lz1998** [comment]
> 看了下这个库封装有点奇怪，不太方便使用。而且测速用的 scp ，没有参考价值，我可能会优先考虑 [cloudflare/boringtun](https://github.com/cloudflare/boringtun)

这个是抄了 boringtun，改成了 tokio 实现（noise 那块还没重构）
