### ISSUE TITLE
IPC error -22: failed to set allowed ip: netip.ParsePrefix("10.xx.xx.108"): no '/'

### ISSUE THREAD

**Issue by fanwenlin** [PinkD/corplink-rs#30]
报错日志：
<img width="935" alt="image" src="https://github.com/PinkD/corplink-rs/assets/17265932/4cd260f7-d4f3-4e80-ab19-d91539f738bc">

添加日志发现，ConnectVPN接口返回的route中，包含了一个没有子网掩码的地址
<img width="849" alt="image" src="https://github.com/PinkD/corplink-rs/assets/17265932/8b452f9f-dea6-40aa-a365-74930cee5531">

**Comment by fanwenlin** [comment]
对这部分末尾添加`/32`之后，可以顺利运行了，不确定这么改是否合适
https://github.com/PinkD/corplink-rs/pull/31

**Comment by PinkD** [comment]
closed by https://github.com/PinkD/corplink-rs/pull/44
