### ISSUE TITLE
[Windows] 请教 Windows 应该怎么 build 4.3？

### ISSUE THREAD

**Issue by chenmin1992** [PinkD/corplink-rs#34]
目前按 Makefile 里的内容，在 Windows powershell 执行相应的命令。

go build wireguard-go 之后，出现 libwg.a 和 libwg.h。
将 libwg.a 和 libwg.h 复制到上层目录，即 corplink-rs\libwg 下。

执行 cargo build --release 时，报找不到 wg.lib。
咨询一 contributor 后重命名 libwg.a 到 wg.lib，之后可以顺利 build 完成。

但是连接的时候卡在
![image](https://github.com/PinkD/corplink-rs/assets/20168118/c94d0f96-9619-4e1c-b4f1-690b0fc4c896)
是我哪里步骤不对么？

麻烦指教，多谢。

**Comment by chenmin1992** [comment]
看代码，卡的位置好像是 [corplink-rs](https://github.com/PinkD/corplink-rs) 无法与 libwg 交互。
正常 mac 能起来是这样的：
![image](https://github.com/PinkD/corplink-rs/assets/20168118/4050ce07-adfe-4b18-a5d9-86da17e9bb69)

**Comment by PinkD** [comment]
windows 有安装虚拟网卡的驱动吗？可以参考官方 wireguard ，要先安装虚拟网卡，然后配置里指定虚拟网卡，才能正常连上的

**Comment by chenmin1992** [comment]
@PinkD 是说 wintun.dll 吗？已经放在 corplink-rs.exe 同目录下了。如果有其他驱动需要安装，麻烦请指出。

刚才试了安装 wireguard windows 客户端后，仍然卡在那里。

**Comment by PinkD** [comment]
安装完 wireguard windows 客户端后，会多出来一个虚拟网卡，将这个虚拟网卡的名字填到配置文件里的 interface name 里应该就行了。在 linux 和 macos 上会自动创建 tun 设备，但是 win 上需要手动安装虚拟网卡来实现

**Comment by gchen08** [comment]
> 安装完 wireguard windows 客户端后，会多出来一个虚拟网卡，将这个虚拟网卡的名字填到配置文件里的 interface name 里应该就行了。在 linux 和 macos 上会自动创建 tun 设备，但是 win 上需要手动安装虚拟网卡来实现

遇到同样的问题，卡在了start wg-corplink。
已经安装了wireguard windows客户端，但只有在建立隧道的时候，才会创建一个wireguard tunnel的interface，断开后也会自动卸载。尝试了通过wg客户端建立隧道后，将创建的interface名写到config.json的interface_name，但并没有效果。

**Comment by chenmin1992** [comment]
> > 安装完 wireguard windows 客户端后，会多出来一个虚拟网卡，将这个虚拟网卡的名字填到配置文件里的 interface name 里应该就行了。在 linux 和 macos 上会自动创建 tun 设备，但是 win 上需要手动安装虚拟网卡来实现
> 
> 遇到同样的问题，卡在了start wg-corplink。 已经安装了wireguard windows客户端，但只有在建立隧道的时候，才会创建一个wireguard tunnel的interface，断开后也会自动卸载。尝试了通过wg客户端建立隧道后，将创建的interface名写到config.json的interface_name，但并没有效果。

+1  断开了 tun 设备就没了

**Comment by PinkD** [comment]
自测没问题，流程：
1. clone 当前仓库
2. 在 libwg 中 clone 魔改版的 wg-go ，然后进去 `go build -trimpath -v -buildmode=c-archive ./libwg` ，把输出的文件放到上层目录(项目根目录下的 `libwg` 目录)
3. `cargo build`
4. 将 `wintun.dll` 放到与编译出来的可执行文件同目录
5. 使用管理员命令执行，程序会自动创建一个 interface name 中定义名字的虚拟网卡
6. 测试内网连通性通过

其中， 3 中用的 `mingw64` 的编译环境，5 之前应该需要装好 wireguard 的虚拟网卡驱动

一些截图：
连接成功。 ping 的图就不放了，里面有 ip 懒得打码
![image](https://github.com/PinkD/corplink-rs/assets/14852537/a0bf3811-1d12-4a2a-ab57-3ecbbf2307a2)
go build 后的结果
![image](https://github.com/PinkD/corplink-rs/assets/14852537/aa32a5d8-9ea2-4355-8690-bbfcc5171b51)
输出的二进制的目录
![image](https://github.com/PinkD/corplink-rs/assets/14852537/807a32a4-7d6a-4763-a958-fe7d3957cdab)

如果上述流程没问题，网不通，有两个比较大的怀疑点。一个是 wireguard 的虚拟网卡驱动是否正常安装，另一个是是否获取并添加上了路由

**Comment by gchen08** [comment]
> 自测没问题，流程：
> 
> 1. clone 当前仓库
> 2. 在 libwg 中 clone 魔改版的 wg-go ，然后进去 `go build -trimpath -v -buildmode=c-archive ./libwg` ，把输出的文件放到上层目录(项目根目录下的 `libwg` 目录)
> 3. `cargo build`
> 4. 将 `wintun.dll` 放到与编译出来的可执行文件同目录
> 5. 使用管理员命令执行，程序会自动创建一个 interface name 中定义名字的虚拟网卡
> 6. 测试内网连通性通过
> 
> 其中， 3 中用的 `mingw64` 的编译环境，5 之前应该需要装好 wireguard 的虚拟网卡驱动
> 
> 一些截图： 连接成功。 ping 的图就不放了，里面有 ip 懒得打码 ![image](https://private-user-images.githubusercontent.com/14852537/336914138-a0bf3811-1d12-4a2a-ab57-3ecbbf2307a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4MjQ4ODIsIm5iZiI6MTcxNzgyNDU4MiwicGF0aCI6Ii8xNDg1MjUzNy8zMzY5MTQxMzgtYTBiZjM4MTEtMWQxMi00YTJhLWFiNTctM2VjYmJmMjMwN2EyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA4VDA1Mjk0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlM2ZlNDFkMzFkNjJkZjJiODFkMmQ4NzMzZmNmYWZkNTVlMTcyNWEwOTJjMTIxNTlmNWU0MmNkNzkyZDc2NzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b4gUJXi8fCGnEDhQSKXMJ1iKChssN0nYYAkFBUbHxfg) go build 后的结果 ![image](https://private-user-images.githubusercontent.com/14852537/336914253-aa32a5d8-9ea2-4355-8690-bbfcc5171b51.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4MjQ4ODIsIm5iZiI6MTcxNzgyNDU4MiwicGF0aCI6Ii8xNDg1MjUzNy8zMzY5MTQyNTMtYWEzMmE1ZDgtOWVhMi00MzU1LTg2OTAtYmJmY2M1MTcxYjUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA4VDA1Mjk0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlYzdkNzdhNWQ0ODc1ZTc5NTA5NDY5MDZmODM3MDA4YTRlNjZlZTI4OTQ5ZmQzODEwODQzMzEwOWUxODkxMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ac5ZmTciD6J1Sl46EXvEdE_KNiKdqaml5XiBXNgvRZo) 输出的二进制的目录 ![image](https://private-user-images.githubusercontent.com/14852537/336915690-807a32a4-7d6a-4763-a958-fe7d3957cdab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4MjQ4ODIsIm5iZiI6MTcxNzgyNDU4MiwicGF0aCI6Ii8xNDg1MjUzNy8zMzY5MTU2OTAtODA3YTMyYTQtN2Q2YS00NzYzLWE5NTgtZmU3ZDM5NTdjZGFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA4VDA1Mjk0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmZDg4MzNkY2FjYmNlNWY5MTE0YzJiODRiN2U1M2ExYzQ4ZjU5MjJmY2FmODJkMTdjM2Q2NWJjNGI4MjQ1YzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6geP3h_TJmlII6yA2IT8CEa1VvrXk2s5Ihrlao5gg30)
> 
> 如果上述流程没问题，网不通，有两个比较大的怀疑点。一个是 wireguard 的虚拟网卡驱动是否正常安装，另一个是是否获取并添加上了路由

感谢指导，已经连通。做了这样2个调整，@chenmin1992 可以参考试试。
- 编译的时候增加跨平台设置，这样不必将`libgw.a`重命名为`wg.lib`
```
rustup target add x86_64-pc-windows-gnu
cargo build --target x86_64-pc-windows-gnu
```
- 使用amd64的`wintun.dll`

启动后遇到一个问题是，从wg_conf里可以看到dns地址，但实际虚拟网卡的DNS没有配上，手动设置即可。

**Comment by chenmin1992** [comment]
> > 自测没问题，流程：
> > 
> > 1. clone 当前仓库
> > 2. 在 libwg 中 clone 魔改版的 wg-go ，然后进去 `go build -trimpath -v -buildmode=c-archive ./libwg` ，把输出的文件放到上层目录(项目根目录下的 `libwg` 目录)
> > 3. `cargo build`
> > 4. 将 `wintun.dll` 放到与编译出来的可执行文件同目录
> > 5. 使用管理员命令执行，程序会自动创建一个 interface name 中定义名字的虚拟网卡
> > 6. 测试内网连通性通过
> > 
> > 其中， 3 中用的 `mingw64` 的编译环境，5 之前应该需要装好 wireguard 的虚拟网卡驱动
> > 如果上述流程没问题，网不通，有两个比较大的怀疑点。一个是 wireguard 的虚拟网卡驱动是否正常安装，另一个是是否获取并添加上了路由
> 
> 感谢指导，已经连通。做了如下调整，@chenmin1992 可以参考试试。
> 
> * 编译的时候增加跨平台设置，这样不必将`libgw.a`重命名为`wg.lib`
> 
> ```
> rustup target add x86_64-pc-windows-gnu
> cargo build --target x86_64-pc-windows-gnu
> ```
> 
> * 使用amd64的`wintun.dll`
> 
> 启动后遇到一个问题是，从wg_conf里可以看到dns地址，但实际虚拟网卡的DNS没有配上，IP也不是自动获取，需要每次启动后再手动设置一次。

感谢大佬指导。通过 `cargo build --target x86_64-pc-windows-gnu` 确实可以 build 出可以连通的 binary。
同样获取不到 DNS，但是可以获取到 IP，内网的网站也可以打开。

但有个问题，可用的 binary 好大。mac build 出来的 9.69MB，`cargo build --release` 出来的 .exe 是 12.8MB，`cargo build --target x86_64-pc-windows-gnu` 的是 138MB。您也是这样的吗？
![image](https://github.com/PinkD/corplink-rs/assets/20168118/cbe945a7-e7ae-4c45-915d-4a5464c2f550)

**Comment by PinkD** [comment]
rust 里 debug 编译出来的很大是正常的， release 会小很多

**Comment by chenmin1992** [comment]
> rust 里 debug 编译出来的很大是正常的， linux 里会带很多符号， windows 应该也是类似。用 release 编译会小很多

感谢。通过 `cargo build --target x86_64-pc-windows-gnu --release` build 出来 13MB。

感谢帮助 rust 新手的打扰。

**Comment by maywine** [comment]
Windows 使用 go1.23 版本编译之后运行有问题：
![image](https://github.com/user-attachments/assets/5a9476d2-a7dc-4f21-8646-b6c73a52460d)

回退到  go1.20.14 则没有问题
