### ISSUE TITLE
亿格云的原理

### ISSUE THREAD

**Issue by godsoul** [PinkD/corplink-rs#40]
想问下，亿格云的原理是不是一样的，主要是搞个虚拟网卡做转发，dns也是他们自己写的

**Comment by PinkD** [comment]
没研究过，你可以先 wireshark 抓包看看数据包长啥样，如果是 udp 就有可能是 wireguard 或者 openvpn ，然后再分析一下包结构就能大概看出来是啥

**Comment by PinkD** [comment]
如果要更进一步，就要 MITM 抓包了
