### ISSUE TITLE
M 系列配置报错 Failed to create TUN device: invalid argument

### ISSUE THREAD

**Issue by bestony** [PinkD/corplink-rs#46]
```
DEBUG: wg-corplink(utun114514123skj) 2024/09/10 10:29:14 Starting wg-corplink version 0.0.20220316-46-ga121834
ERROR: wg-corplink(utun114514123skj) 2024/09/10 10:29:14 Failed to create TUN device: invalid argument
```

启动命令：`corplink-rs /etc/corplink-rs/config.json`, config 的局部内容如下

```
{
  "interface_name": "utun114514123skj",
  "device_name": "DollarOS",
  "debug_wg": true,
  "state": "Login",
  "vpn_server_name": null,
  "vpn_select_strategy": null
}
```

**Comment by PinkD** [comment]
请参考 README 中「macos 特殊说明」章节

**Comment by bestony** [comment]
调整后也没有用

```
➜  ~ RUST_BACKTRACE=1 corplink-rs /etc/corplink-rs/config.json
DEBUG: wg-corplink(utun1145141) 2024/09/11 08:44:29 Starting wg-corplink version 0.0.20220316-46-ga121834
ERROR: wg-corplink(utun1145141) 2024/09/11 08:44:29 Failed to create TUN device: invalid argument
```
可以看到这里的 device name 是 `utun1145141` ，符合 macOS 的特殊说明要求。

**Comment by PinkD** [comment]
1. 系统版本
2. corplink-rs 版本
3. 是否使用 root 权限启动本程序

**Comment by bestony** [comment]
1. 已经是 root

<img width="572" alt="图片" src="https://github.com/user-attachments/assets/dbc1e09a-5568-4495-a982-c0982fbfb4ec">

2. 系统 14.6.1 (23G93)
3. corp-link-rs 0.5.0 最新的 master 1e98c16a0878c45ad5027040b2c9b243b81366fd

**Comment by PinkD** [comment]
经过测试， macos 的 utun 接口后的 index 类型应该为 `int16` ，即最高为 `32767` ，改成小于等于这个数即可

**Comment by PinkD** [comment]
https://opensource.apple.com/source/xnu/xnu-4570.1.46/bsd/net/if_utun.c.auto.html
网上搜到的关联的源码里是 `uint32` 类型，不清楚是什么歌情况
