### ISSUE TITLE
咨询use_vpn_dns 相关问题

### ISSUE THREAD

**Issue by jixiuf** [PinkD/corplink-rs#49]
我看有个 use_vpn_dns 的开关 只能在macos 上用，
 
是 只有macos 需要这个功能？ 还是说只选择实现了macos版的，linux 无法实现？

我发现一个问题，公司内网一些域名无法解析，或者是这个原因导致的

如果我想支持使用vps 的dns 来解析域名，linux 上有什么思路吗。

**Comment by PinkD** [comment]
linux 上可以通过替换 `/etc/resolv.conf` 实现。你也可以拿到 dns 后手动操作

**Comment by PinkD** [comment]
可以参考这个仓库的这个 commit
https://github.com/TundraWork/corplink/commit/cf6f640cf2771f66d06d65549028f73588031b7d

**Comment by PinkD** [comment]
替换 dns 对于有透明代理的人来说是一个非常 annoying 的操作，所以我暂时没有加上这个功能的打算。如果你需要这个功能，欢迎提 pr
