### ISSUE TITLE
Support for Running corplink-rs as VPN on Android?

### ISSUE THREAD

**Issue by shanehh** [PinkD/corplink-rs#51]
Thank you for your hard work. The `corplink-rs` works really well on my computer (MacOS). I want to ask if it's possible to run it on an Android device? Sorry for my lack of knowledge, but I don’t know how to do that.

If it’s possible, could you describe the high-level procedure for making `corplink-rs` work on an Android device? This would be really helpful. Thanks!

**Comment by PinkD** [comment]
Theoretically yes. Spawning a vpn tun device on Android and configure it with wireguard-go.
Also, an App is needed for better experience.
But obviously, there're tons of works needed to be done to implement that. So there's no plan for that.
