### ISSUE TITLE
如何通过飞书授权登录

### ISSUE THREAD

**Issue by marlonfan** [PinkD/corplink-rs#7]
目前的方案是基于ldap来进行登录的。 在策略里面被禁用了, 只允许飞书授权登录。 是否有模式可以兼容?

**Comment by PinkD** [comment]
没做过这种三方登录的功能，不太清楚怎么调用的
我抓包看了下，飞连直接就打开了一个飞书连接跳转到飞书，然后飞书登录确认过后就能拿到一个 token 返回给飞连，但是这个链接怎么拿到， token 怎么回传，都不清楚
你有啥思路吗

**Comment by PinkD** [comment]
研究了一下，感觉应该比较简单，就是需要用户点击链接手动验证一下，我这两天抽空做一下

**Comment by marlonfan** [comment]
非常感谢~

**Comment by PinkD** [comment]
试试 3.3 版本，配置文件里 `platform` 填 `lark` ，然后需要点击打印出来的链接用飞书软件授权，完成后回命令行敲一下换行继续。应该之用登录一次
第三方登录的情况下，用户名应该是不用输入的，我忘了删，你随便填啥都行

**Comment by marlonfan** [comment]
![image](https://user-images.githubusercontent.com/9349370/203108406-c08f888f-7fc7-4dfb-993e-764430b80f67.png)
登陆成功, wg启动成功, 静态路由写入成功. 但是无法ping通

**Comment by marlonfan** [comment]
![image](https://user-images.githubusercontent.com/9349370/203111867-f4442942-6290-4ac2-a927-b8fbdac91441.png)
我猜测是不是因为gw这里被设置的是0.0.0.0 不是`corplink`网卡的实际地址?

我有什么其他的方式可以排查这个问题么?

**Comment by PinkD** [comment]
这是跑在什么平台上的？ windows ？为什么我看 unix socket 是 `/var/run/wireguard/corplink.sock` ，在 win 上应该是在用户的 temp 目录下才对

**Comment by marlonfan** [comment]
是在linux上面，ubuntu. 因为windows需要特殊配置，所以直接用linux了，后面加个流量转发就可以了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: PinkD ***@***.***&gt;
发送时间: 2022年11月22日 00:52
收件人: PinkD/corplink-rs ***@***.***&gt;
抄送: marlon ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [PinkD/corplink-rs] 如何通过飞书授权登录 (Issue #7)





 
这是跑在什么平台上的？ windows ？为什么我看 unix socket 是 /var/run/wireguard/corplink.sock ，在 win 上应该是在用户的 temp 目录下才对

**Comment by PinkD** [comment]
linux 上看路由用 `ip route` ，但是看起来是没问题的，这种 p2p 接口，只需要 `ip route add xxx/xxx dev xxx` 就可以了，并不需要 gateway ，另外， wg 的连接状态正常吗，我是指有没有正常收发到握手包

**Comment by marlonfan** [comment]
![image](https://user-images.githubusercontent.com/9349370/203487627-afe8a755-6297-40ff-98da-41bc8815819d.png)
看上去心跳包没啥问题.

**Comment by PinkD** [comment]
内网机器(10.0.0.1)的业务端口(22)能正常访问吗，会不会是机器禁 ping ，可以先看一下路由有没有选对，再用 mtr 看一下包有没有出去：
```bash
ip route get 10.0.0.1
mtr -n -T -P 22 10.0.0.1
```

**Comment by PinkD** [comment]
飞书登录功能已经可用了，这个 issue 先关闭了吧，如果有其它问题，新开一个 issue 或者用其它联系方式私聊吧
